but_30725
******************************************************************************************
Thanks a lot to Jeremy for his vprobes script. Saved me lot of time.

~ # vprobe /tmp/cwd.emt | grep KFP6Q7
   5357449             localcli 1:8 bin/3.0.0.1-27390_51385e5/bundles/datrium-KFP6Q7/


 ps -cusv | grep 5357449
5357449   5357449  localcli              WAIT    VMKAPI  0-47  /sbin/localcli storage core device smart get -d naa.55cd2e404c746e38
16502658  16502658  grep                  WAIT    UPIPER  0-47  grep 5357449
~ #
~ # vmware -l
VMware ESXi 6.0.0 Update 2

vprobes can be found in Scripts/vprobes/cwd.emt

******************************************************************************************
but_30780
******************************************************************************************
# restart syslog
/vmfs/volumes/5a58241d-1df69072-850d-002590f966e8/log # esxcli system syslog reload

[node1.controller1-RMS0993933G00FP: ~]# hosts show
# http://confluence.datrium.com/display/KNOW/How+to+restart+vmkernel+logging+on+ESXi

~ # ps -Cc | grep vmsyslogd
216626209 216626209 grep                 grep vmsyslogd
216508223 216508223 vmsyslogd            /bin/python -OO /usr/lib/vmware/vmsyslog/bin/vmsyslogd.pyo
213264190 213264190 wdog-216508223       /bin/python -OO /usr/lib/vmware/vmsyslog/bin/vmsyslogd.pyo
~ # kill -9 216508223
~ # kill -9 213264190
sh: can't kill pid 213264190: No such process
~ # /usr/lib/vmware/vmsyslog/bin/vmsyslogd
Second fork failed 28 (No space left on device)
~ # df -h
Filesystem   Size   Used Available Use% Mounted on
NFS          4.0T   1.9T      2.1T  47% /vmfs/volumes/ISO
NFS        110.5T  32.7T     77.8T  30% /vmfs/volumes/b21-Datastore1
NFS          0.0B   0.0B      0.0B   0% /vmfs/volumes/cores
NFS         49.1G   4.5G     44.6G   9% /vmfs/volumes/esxtop
VMFS-5      14.8G   1.3G     13.4G   9% /vmfs/volumes/datrium-reserved-sys-b21-pesx02_00:25:90:f9:d7:84-MP5L2E
VMFS-5      14.8G   7.6G      7.1G  52% /vmfs/volumes/datrium-reserved-sys-b21-pesx02_00:25:90:f9:d7:84-BTCOHB
VMFS-5     121.0G   8.8G    112.2G   7% /vmfs/volumes/datrium-reserved-core-b21-pesx02_00:25:90:f9:d7:84-OPZ3WG
vfat         4.0G  96.6M      3.9G   2% /vmfs/volumes/54cfae62-c59fcafb-3279-002590f9d784
vfat       249.7M 172.9M     76.8M  69% /vmfs/volumes/9cdfd27d-61403786-7750-bced9f9d7739
vfat       249.7M 210.6M     39.1M  84% /vmfs/volumes/c49bc07c-b9e365b2-3488-78ee4ae771fc
vfat       285.8M 193.4M     92.4M  68% /vmfs/volumes/54cfae58-97750396-7b24-002590f9d784

******************************************************************************************
but_30785
******************************************************************************************
lsi_megaraid.log


******************************************************************************************
live core
******************************************************************************************
# procmgr_cli.py show

Mode/Changing: 3/False

Name                   Stat  PID      Auto  Enable Modes        Vmsize    RSS  Uptime
---------------------------------------------------------------------------------
DaggerWorker           R     19737331 1     1      3                 0      0   1d 0h
ESXPlatMgr             R     41450257 1     1      3                 0      0   6d 5h
FE                     R     41417488 1     1      3                 0      0   6d 5h
eventproducer          R     41450258 1     1      3                 0      0   6d 5h
NetworkHeartbeat       R     41450090 1     1      2,3               0      0   6d 5h
UpgradeMgr             R     41450089 1     1      2,3               0      0   6d 5h
FEMountd               R     41449753 1     1      1,2,3             0      0   6d 5h
esx_platmgr            R     41449752 1     1      1,2,3             0      0   6d 5h
---------------------------------------------------------------------------------
Total                                                                0      0        
[root@n1631-a07n2:~] vsish
/world/41449752/> cd /userworld/
/userworld/> ls
info
destroy
global/
groups/
groupPathStringToID
groupPathNameToID
mem/
stats/
cartel/
/userworld/> cd /
/> cd /usre
/userworld/> cd /userworld/cartel/
/userworld/cartel/> cd ..
/userworld/> ls
info
destroy
global/
groups/
groupPathStringToID
groupPathNameToID
mem/
stats/
cartel/
/userworld/> cd cartel
/userworld/cartel/> ls
46560327/
47412077/
47444832/
...

/userworld/cartel/> cd 41449752
/userworld/cartel/41449752/> ls
loglevels/
stats/
resetStats
debug/
net/
mem/
fss/
fd/
signal/
thread/
child/
parent
netstack
vmmLeader
leader
arch
cmdline
/userworld/cartel/41449752/> cd debug
/userworld/cartel/41449752/debug/> ls
livecore
coreDumpEnabled
/userworld/cartel/41449752/debug/> set /userworld/cartel/41449752/debug/livecore 1
/userworld/cartel/41449752/debug/> quit
[root@n1631-a07n2:~] cd /var/core
[root@n1631-a07n2:/vmfs/volumes/595308a3-3658244b-3dd7-0cc47a907816/core] ls
FE-1-flat.vswp    python-zdump.000
[root@n1631-a07n2:/vmfs/volumes/595308a3-3658244b-3dd7-0cc47a907816/core] ls -al
total 8689672
drwxr-xr-x    1 root     root           560 Dec  5 23:57 .
drwxr-xr-t    1 root     root          1540 Jun 28 01:38 ..
-rw-------    1 root     root     8884584448 Nov 29 18:36 FE-1-flat.vswp
-r--------    1 root     root      11870208 Dec  5 23:57 python-zdump.000

**********************************************
where is python
**********************************************
/da/ToolsAndLibs/LinuxX64ToEsxX64/python2-2.7.12/bin
cp ~/colo01/da/ToolsAndLibs/LinuxX64ToEsxX64/Python-2.7.12.da1/bin/python .

/da/ToolsAndLibs/LinuxX64ToLinuxX64/gdb-7.10.da1/bin/gdb -q -iex "set sysroot /tmp/esx-sysroot" ./python python-core.00
set solib-search-path /da/ToolsAndLibs/LinuxX64ToEsxX64/Python-2.7.12/lib/python2.7/lib-dynload

source /da/ToolsAndLibs/LinuxX64ToLinuxX64/Python-2.7.12/python-gdb.py

/auto/home/jeremy$cat .gdbinit
set print pretty on
set pagination off
set print demangle
set print asm-demangle
set solib-search-path /da/pydbg/lib/python2.7/lib-dynload
source /da/pydbg/python-gdb.py
source /da/main/Scripts/gdbpython.py

(gdb) source /da/ToolsAndLibs/LinuxX64ToLinuxX64/Python-2.7.12/python-gdb.py
(gdb) py-bt
Traceback (most recent call first):
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 359, in wait
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 614, in wait
  File "/opt/datrium/PythonRoot/datrium/platform/esx/esx_kvstore.py", line 789, in _disk_io_thread_run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 754, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap
(gdb) t a a py-bt

Thread 9 (LWP 41449865):
Traceback (most recent call first):
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 359, in wait
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 614, in wait
  File "/opt/datrium/PythonRoot/datrium/platform/esx/esx_hostd.py", line 97, in _keep_hostd_connection_alive
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 754, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap

Thread 8 (LWP 41449864):
Traceback (most recent call first):
  File "/opt/datrium/PythonRoot/datrium/platform/common/event_loop.py", line 213, in run
  File "/opt/datrium/PythonRoot/datrium/platform/raid_mgr/raid_mgr.py", line 120, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap

Thread 7 (LWP 41449863):
Traceback (most recent call first):
  File "/opt/datrium/PythonRoot/datrium/platform/common/event_loop.py", line 213, in run
  File "/opt/datrium/PythonRoot/datrium/platform/ssd_mgr/ssd_mgr.py", line 821, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap

Thread 6 (LWP 41449862):
Traceback (most recent call first):
  File "/opt/datrium/PythonRoot/datrium/platform/esx/esx_config.py", line 288, in wait_for_change
  File "/opt/datrium/PythonRoot/datrium/platform/esx/advcfg_listener.py", line 464, in listen_for_updates
  File "/opt/datrium/PythonRoot/datrium/platform/esx/advcfg_listener.py", line 78, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 754, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap

Thread 5 (LWP 41449845):
Traceback (most recent call first):
  Waiting for the GIL
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 340, in wait
  File "/opt/datrium/bin/esx_platmgr.py", line 105, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap

Thread 4 (LWP 45943497):
Traceback (most recent call first):
  Waiting for the GIL
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 340, in wait
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 614, in wait
  File "/opt/datrium/PythonRoot/datrium/logging/directio.py", line 144, in _flusher_thread_run
---Type <return> to continue, or q <return> to quit---
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 754, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap

Thread 3 (LWP 41449816):
Traceback (most recent call first):
  File "/opt/datrium/PythonRoot/datrium/platform/esx/esx_kvstore.py", line 739, in _symlink_to_paths_or_wait
  File "/opt/datrium/PythonRoot/datrium/platform/esx/esx_kvstore.py", line 770, in _disk_io_thread_run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 754, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap

Thread 2 (LWP 41449752):
Traceback (most recent call first):
  File "/opt/datrium/python2/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
  File "/opt/datrium/python2/lib/python2.7/subprocess.py", line 1319, in _execute_child
  File "/opt/datrium/python2/lib/python2.7/subprocess.py", line 711, in __init__
  File "/opt/datrium/PythonRoot/datrium/utils/vsi.py", line 40, in _check_output
  File "/opt/datrium/PythonRoot/datrium/utils/vsi.py", line 66, in get
  File "/opt/datrium/PythonRoot/datrium/platform/esx/esx_net.py", line 243, in monitor_network
  File "/opt/datrium/PythonRoot/datrium/platform/common/event_loop.py", line 222, in run
  File "/opt/datrium/bin/esx_platmgr.py", line 1365, in platmgr_main
  File "/opt/datrium/bin/esx_platmgr.py", line 1472, in main
  File "/opt/datrium/bin/esx_platmgr.py", line 1489, in <module>

Thread 1 (LWP 41449815):
Traceback (most recent call first):
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 359, in wait
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 614, in wait
  File "/opt/datrium/PythonRoot/datrium/platform/esx/esx_kvstore.py", line 789, in _disk_io_thread_run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 754, in run
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/datrium/python2/lib/python2.7/threading.py", line 774, in __bootstrap

**********************************************
live dump 34130
**********************************************
localcli --plugin-dir /usr/lib/vmware/esxcli/int/ debug livedump perform

